version: '3'
services:
    api:
        image: ok-api
# relevant if you want to directly access the api from outside the app
#        ports:
#            - 8080:8080
    app:
        depends_on:
            - api
        image: ok-app
        ports:
            - 80:80
        links:
            - api
